src/compliment/utils.clj
Fixes https://github.com/clojure-emacs/cider/issues/1870
Do you need test for this? I wasn't quite sure how to write them. You can create a directory structure like:
```
foo/
xxx/
bar -> ../../bar (symlink)
bar/
yyy/
foo -> ../../foo (symlink)
```
Running `(file-seq (File. "foo"))` as `compliment.utils/list-files` does, will return an infinite sequence. Trying to consume it will likely lead to OOM.
=> Use non-recursive version of file-seq

src/compliment/sources/class_members.clj, test/compliment/sources/t_class_members.clj
`members-candidates` does not pass `ns` to `try-get-object-class`, so it does not find vars in different namespaces. Also if there is a var of the same name on the current namespace, it can produce incorrect results.
This patch simply changes `resolve` to `ns-resolve`.
=> Fix members-candidates to work with vars on different namespaces

src/compliment/sources/keywords.clj, test/compliment/sources/t_keywords.clj
When completing keywords, the presence of double colons and a slash
assumed that there was a namespace alias separating the two. We catch
the (infrequent) situation of that not being the case, as this threw
an error when the user was typing
re: https://github.com/alexander-yakushev/compliment/issues/46
=> Guard against namespace aliases with no namespace

src/compliment/utils.clj, test/compliment/t_utils.clj
https://github.com/alexander-yakushev/compliment/issues/50
look for aliases before fully qualified. really only matters for anything aliased as `user`
=> Correctly resolve namespaces aliased as `user`

.travis.yml, src/compliment/utils.clj
clojure.lang.Reflector is getting more strict, causing it to not
find the call to `.forEach`. By adding a type hint the reflection
goes away.
=> Fix Clojure 1.10 compatibility issue

src/compliment/core.clj
Just remove unused `sort-fn` at `compliment.core/completions`
=> Remove unused `sort-fn`

project.clj, src/compliment/sources/cljs.cljc, src/compliment/sources/cljs/analysis.cljc, src/compliment/sources/ns_mappings.clj, src/compliment/utils.clj, test-resources/compliment/cljs/env.cljc, test-resources/compliment/test_macros.clj, test-resources/compliment/test_ns.cljs, test-resources/compliment/test_ns_dep.cljs, test/compliment/sources/t_cljs.cljc, test/compliment/sources/t_keywords.clj, test/compliment/t_core.clj
This PR shows what CLJS completions look like.
The code is ported from `cljs-tooling` - what is used by Cider for ClojureScript completions.
The goal here is to end up with the same public api and behavior. Probably some
of the Compliment options would not apply in which case, please, advice :smile:
I am always open to tweaks of any sort, just send any feedback over.
=> Port the cljs-tooling completion machinery to compliment

src/compliment/core.clj
This patch makes sure we can pass the same (optional) options-map do the
documentation function, which now accepts source keywords.
=> [Fix #69] Introduce options-map and add sources feature to core/documentation

src/compliment/utils.clj
It removes the following annoying reflection warnings while using the cider-repl:
```
Reflection warning, compliment/utils.clj:160:15 - reference to field findAll on java.lang.Object can't be resolved.
Reflection warning, compliment/utils.clj:168:51 - reference to field list on java.lang.Object can't be resolved.
Reflection warning, compliment/utils.clj:170:7 - reference to field close on java.lang.Object can't be resolved.
Reflection warning, compliment/utils.clj:168:51 - reference to field list on java.lang.Object can't be resolved.
Reflection warning, compliment/utils.clj:170:7 - reference to field close on java.lang.Object can't be resolved.
```
all test pass with JDK8 and JDK9+
=> Remove reflection warnings

.circleci/config.yml, project.clj, src/compliment/utils.clj, test/compliment/sources/t_resources.clj, test/compliment/t_utils.clj
I was unsure about whether `classes-on-classpath` was comprehensive so I coded a test for it, particularly for a few cases that I particuarly cared about.
While I was there I also added a few CI improvements. Commits:
* `Add classes-on-classpath-test`
* Add JDK17 to the test matrix
* CI: use Eastwood within each JDK
* Eastwood, being runtime-powered, can provide additional insights this way.
* Upgrade Eastwood
* Use Clojure 1.10.3
I have a green build in my account https://app.circleci.com/pipelines/github/reducecombine/compliment
Cheers - V
=> Add `classes-on-classpath-test`

src/compliment/sources/ns_mappings.clj, test/compliment/t_core.clj
Hi Alex,
it seemed to me that completions could be offered for quoted or var-quoted symbols.
Examples included as deftests.
The proposed solution is not particularly fancy, it might not be even be located in the best place but it might be at least a good conversation starter!
Build is green in my account:
Best wishes 🇺🇦
=> Also offer completions for (var-) quoted symbols

CHANGELOG.md, src/compliment/context.clj, src/compliment/sources/local_bindings.clj, test/compliment/sources/t_local_bindings.clj, test/compliment/t_context.clj
First of all, thank you for developing and maintaining 'compliment'.
I found problems related to namespaced keywords:
- `compliment.context/try-read-replacing-maps` return `nil` if aliased namespace keywords(e.g. `::my-ns/keyword`) are contained in context string. (`read-str` try to resolve the alias)
I changed `try-read-replacing-maps` to replace aliased namespace keyword to namespaced keyword(e.g. `:my-ns/keyword`) to avoid the problem.
- `compliment.sources.local-bindings/parse-binding` ignore variables that destructuring the map with namespaced keywords:
```clj
(require '[instaparse.gll :as gll])
(let [#_..., {::gll/keys [start-index end-index]} (meta x)])
```
I changed `parse-binding` to handle namespaced keywords.
=> Fix for namespaced keywords

CHANGELOG.md, src/compliment/context.clj, test/compliment/t_context.clj
In `try-read-replacing-maps` function, in order to read a context, replace '{' and '}' with '(compliment-hashmap' and ')' respectively without condition.
'\\{' (literal '{') is also replaced with '\\(compliment-hashmap'. (`read-string` cannot parse a string containing '\\('.)
So if a context contains '{' or '}', can't extract variable names from the context due to `safe-read-context-string` return `nil`.
To avoid the problem, I fixed `try-read-replacing-maps` to replace '\\{' and '\\}' with '(char 123)' and '(char 125)' respectively before replacing '{' and '}'.
```clojure
;; before changes:
(criterium.core/quick-bench (try-read-replacing-maps "(defn glob->regex
\"Convert a glob pattern string to a regular expression.
I additionally support '**' pattern. This pattern indicates all …
```
=> Workaround to avoid to replace '\{' and '\}' to '\(compliment-hashmap' and '\)' respectively

src/compliment/sources/namespaces_and_classes.clj
Changes `(comp distinct concat)` -> `(into [] (comp cat (distinct)) [,,,])` which should be slightly faster and take less memory.
Cheers - V
=> Slightly optimize `compliment.sources.namespaces-and-classes/candidates`

CHANGELOG.md, src/compliment/sources/namespaces_and_classes.clj, src/compliment/utils.clj, test/compliment/sources/t_namespaces_and_classes.clj, test/compliment/t_core.clj, test/compliment/t_utils.clj, test/dummy.cljs
=> Also consider cljc files for namespaces-on-classpath

CHANGELOG.md, src/compliment/sources/namespaces_and_classes.clj, src/compliment/sources/ns_mappings.clj, src/compliment/utils.clj, test/compliment/sources/t_namespaces_and_classes.clj, test/compliment/sources/t_ns_mappings.clj
Addresses 1, 2 and 3 as described in #95
=> Completion and documentation with leading literals

CHANGELOG.md, src/compliment/sources/ns_mappings.clj, test/compliment/sources/t_ns_mappings.clj
This PR adds two things:
- the earlier discussed suggestion of private vars when using `#'some-ns/,,,`
- adding a `:deprecated` key to suggested vars and functions
=> Suggest private vars

CHANGELOG.md, project.clj, src/compliment/context.clj, src/compliment/core.clj, src/compliment/sources/class_members.clj, src/compliment/sources/local_bindings.clj, src/compliment/utils.clj, test/compliment/sources/t_class_members.clj, test/compliment/sources/t_local_bindings.clj
> Closes https://github.com/alexander-yakushev/compliment/issues/61
Introduces support for ->, ->> and doto, by macroexpanding things in a sensible and constrained manner.
~(also .., but code coverage is pending atm)~
Other refinements are introduced so that ->/doto is actually useful. In specific terms, types are now better propagated/perceived when encountering vars, and `let` bindings (note: doto expands to a `let`, which is why it's important), etc.
Build is green:
Looking forward to feedback.
Cheers - V
=> Recognize target class within ->, ->>, doto

CHANGELOG.md, src/compliment/sources/class_members.clj, src/compliment/sources/local_bindings.clj, src/compliment/utils.clj, test/compliment/sources/t_class_members.clj, test/compliment/sources/t_local_bindings.clj
Fixes https://github.com/alexander-yakushev/compliment/issues/106
Hopefully the inclusion of colls won't be a nuisance - as you can see, luckily it turned out to be a minimal addition.
Most pragmatically, it would be used in https://github.com/clojure-emacs/cider-nrepl/issues/812 for instance.
Cheers - V
=> Infer the class of string and coll literals

CHANGELOG.md, src/compliment/core.clj, src/compliment/sources.clj, src/compliment/sources/class_members.clj, src/compliment/sources/classes.clj, src/compliment/sources/namespaces.clj, src/compliment/sources/vars.clj, test/compliment/sources/t_class_members.clj, test/compliment/sources/t_classes.clj, test/compliment/sources/t_namespaces.clj, test/compliment/sources/t_vars.clj, test/compliment/t_core.clj, test/compliment/t_helpers.clj
This feature allows sources to influence the final candidate order within the same source or across sources.
=> [sources] Add support for candidate priorities

CHANGELOG.md, src/compliment/sources/keywords.clj, test/compliment/sources/t_keywords.clj
E.g. if you have `(require '[foo.core :as foo])`, then:
```clj
::f█ 
=> 
::foo/
```
=> [c.s.keywords] Append / to ::ns-alias/ completions

CHANGELOG.md, src/compliment/sources/namespaces.clj, test/compliment/sources/t_namespaces.clj, test/compliment/t_core.clj
```
(require '[clojure.string :as str])
st█
=>
str/
```
=> [c.s.namespaces] Append / to namespace alias completions
